# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:  ### job runs maven build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: upload project
      uses: actions/upload-artifact@v2
      with:
        name: github-workflow-sample2.jar
        path: target/



  release-project:  ### create release in github
    name: release demo project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: git init   ## initialize git before bumping. as entrypoin.sh runs git command which gets fail if its not a git directroy

      - uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Bump version and push tag   ## set release version default version will be 0.0.0. we can overwrite it with env variable "INITIAL_VERSION"
        id: set_version
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: create github release   ## create github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: release ${{ github.ref_name }}
          body: ${{ steps.set_version.outputs.new_tag }}
          draft: false

      - name: download project
        uses: actions/download-artifact@v3
        with:
          name: github-workflow-sample2.jar

      - name: upload assets to github release   ## upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./github-workflow-sample2.jar
          asset_name: github-workflow-sample2.jar
          asset_content_type: application/java-archive


  build-container:  ### create docker container image and push to repository
    name: build docker container image
    runs-on: ubuntu-latest
    needs: release-project
    steps:
      - uses: actions/checkout@v3   ## checkout

      - name: Build and push docker image   ## create image and push to docker repository
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rvkmrwagh/github-workflow-sample2
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
